// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/fingerprint.proto

package fingerprint

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1375a960f33bea28, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string   `protobuf:"bytes,3,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1375a960f33bea28, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1375a960f33bea28, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "CreateUserResponse")
}

func init() { proto.RegisterFile("pb/fingerprint.proto", fileDescriptor_1375a960f33bea28) }

var fileDescriptor_1375a960f33bea28 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0xb5, 0xda, 0x15, 0x1d, 0x4f, 0x8e, 0x15, 0xea, 0x9e, 0x24, 0x27, 0x4f, 0x59, 0xd9, 0x1e,
	0xfc, 0x01, 0x05, 0x6f, 0x5e, 0x2a, 0x9e, 0x25, 0x6d, 0xa7, 0x12, 0xb0, 0x49, 0x9c, 0x24, 0x0a,
	0xfe, 0x7a, 0x31, 0xda, 0x6d, 0xa1, 0xb7, 0x79, 0x1f, 0x79, 0x8f, 0x17, 0x28, 0x5c, 0xbb, 0x1b,
	0xb4, 0x79, 0x23, 0x76, 0xac, 0x4d, 0x90, 0x8e, 0x6d, 0xb0, 0xe2, 0x1e, 0xf2, 0x17, 0x4f, 0x8c,
	0x08, 0x79, 0x8c, 0xba, 0x2f, 0xb3, 0xdb, 0xec, 0xee, 0xbc, 0x49, 0x37, 0x16, 0xb0, 0xa1, 0x51,
	0xe9, 0xf7, 0xf2, 0x38, 0x91, 0x7f, 0x40, 0x7c, 0xc3, 0x65, 0xcd, 0xa4, 0x02, 0xfd, 0xbe, 0x6b,
	0xe8, 0x23, 0x92, 0x0f, 0xb3, 0x35, 0x5b, 0x58, 0x71, 0x0b, 0x67, 0x4e, 0x79, 0xff, 0x65, 0xb9,
	0xff, 0xcf, 0x38, 0x60, 0xac, 0xe0, 0x7a, 0xba, 0x5f, 0x3b, 0x6b, 0x06, 0xcd, 0xa3, 0x0a, 0xda,
	0x9a, 0xf2, 0x24, 0x19, 0x8b, 0x49, 0xac, 0x17, 0x9a, 0xd8, 0x01, 0x2e, 0xbb, 0xbd, 0xb3, 0xc6,
	0x13, 0xde, 0x40, 0x1e, 0x3d, 0x71, 0xea, 0xbe, 0xd8, 0x6f, 0x64, 0x12, 0x13, 0xb5, 0x7f, 0x02,
	0x7c, 0x9c, 0x37, 0x3f, 0x13, 0x7f, 0xea, 0x8e, 0xf0, 0x01, 0x60, 0x8e, 0x41, 0x94, 0xab, 0x3d,
	0xdb, 0x2b, 0xb9, 0xee, 0x11, 0x47, 0xed, 0x69, 0xfa, 0xb4, 0xea, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x03, 0x17, 0x10, 0x1d, 0x4c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FingerprintServiceClient is the client API for FingerprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FingerprintServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type fingerprintServiceClient struct {
	cc *grpc.ClientConn
}

func NewFingerprintServiceClient(cc *grpc.ClientConn) FingerprintServiceClient {
	return &fingerprintServiceClient{cc}
}

func (c *fingerprintServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/FingerprintService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FingerprintServiceServer is the server API for FingerprintService service.
type FingerprintServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

func RegisterFingerprintServiceServer(s *grpc.Server, srv FingerprintServiceServer) {
	s.RegisterService(&_FingerprintService_serviceDesc, srv)
}

func _FingerprintService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FingerprintService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FingerprintService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FingerprintService",
	HandlerType: (*FingerprintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _FingerprintService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/fingerprint.proto",
}
