// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fingerprint.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateSessionResponse_Status int32

const (
	CreateSessionResponse_SUCCESSFUL        CreateSessionResponse_Status = 0
	CreateSessionResponse_PASSWORD_MISMATCH CreateSessionResponse_Status = 1
)

var CreateSessionResponse_Status_name = map[int32]string{
	0: "SUCCESSFUL",
	1: "PASSWORD_MISMATCH",
}

var CreateSessionResponse_Status_value = map[string]int32{
	"SUCCESSFUL":        0,
	"PASSWORD_MISMATCH": 1,
}

func (x CreateSessionResponse_Status) String() string {
	return proto.EnumName(CreateSessionResponse_Status_name, int32(x))
}

func (CreateSessionResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{7, 0}
}

type ResetUserPasswordResponse_Status int32

const (
	ResetUserPasswordResponse_SUCCESSFUL              ResetUserPasswordResponse_Status = 0
	ResetUserPasswordResponse_PASSWORD_MISMATCH       ResetUserPasswordResponse_Status = 1
	ResetUserPasswordResponse_NO_MATCHING_RESET_TOKEN ResetUserPasswordResponse_Status = 2
)

var ResetUserPasswordResponse_Status_name = map[int32]string{
	0: "SUCCESSFUL",
	1: "PASSWORD_MISMATCH",
	2: "NO_MATCHING_RESET_TOKEN",
}

var ResetUserPasswordResponse_Status_value = map[string]int32{
	"SUCCESSFUL":              0,
	"PASSWORD_MISMATCH":       1,
	"NO_MATCHING_RESET_TOKEN": 2,
}

func (x ResetUserPasswordResponse_Status) String() string {
	return proto.EnumName(ResetUserPasswordResponse_Status_name, int32(x))
}

func (ResetUserPasswordResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{11, 0}
}

type GetUserRequest struct {
	// Types that are valid to be assigned to Identifier:
	//	*GetUserRequest_Uuid
	//	*GetUserRequest_Email
	Identifier           isGetUserRequest_Identifier `protobuf_oneof:"identifier"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

type isGetUserRequest_Identifier interface {
	isGetUserRequest_Identifier()
}

type GetUserRequest_Uuid struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type GetUserRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*GetUserRequest_Uuid) isGetUserRequest_Identifier() {}

func (*GetUserRequest_Email) isGetUserRequest_Identifier() {}

func (m *GetUserRequest) GetIdentifier() isGetUserRequest_Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *GetUserRequest) GetUuid() string {
	if x, ok := m.GetIdentifier().(*GetUserRequest_Uuid); ok {
		return x.Uuid
	}
	return ""
}

func (m *GetUserRequest) GetEmail() string {
	if x, ok := m.GetIdentifier().(*GetUserRequest_Email); ok {
		return x.Email
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetUserRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetUserRequest_OneofMarshaler, _GetUserRequest_OneofUnmarshaler, _GetUserRequest_OneofSizer, []interface{}{
		(*GetUserRequest_Uuid)(nil),
		(*GetUserRequest_Email)(nil),
	}
}

func _GetUserRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetUserRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *GetUserRequest_Uuid:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Uuid)
	case *GetUserRequest_Email:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Email)
	case nil:
	default:
		return fmt.Errorf("GetUserRequest.Identifier has unexpected type %T", x)
	}
	return nil
}

func _GetUserRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetUserRequest)
	switch tag {
	case 1: // identifier.uuid
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &GetUserRequest_Uuid{x}
		return true, err
	case 2: // identifier.email
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &GetUserRequest_Email{x}
		return true, err
	default:
		return false, nil
	}
}

func _GetUserRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetUserRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *GetUserRequest_Uuid:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Uuid)))
		n += len(x.Uuid)
	case *GetUserRequest_Email:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Email)))
		n += len(x.Email)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserRequest struct {
	Email                string           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string           `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string           `protobuf:"bytes,3,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	ScopeGroupings       []*ScopeGrouping `protobuf:"bytes,4,rep,name=scope_groupings,json=scopeGroupings,proto3" json:"scope_groupings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *CreateUserRequest) GetScopeGroupings() []*ScopeGrouping {
	if m != nil {
		return m.ScopeGroupings
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{3}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CreateGuestUserRequest struct {
	Email                string           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ScopeGroupings       []*ScopeGrouping `protobuf:"bytes,2,rep,name=scope_groupings,json=scopeGroupings,proto3" json:"scope_groupings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateGuestUserRequest) Reset()         { *m = CreateGuestUserRequest{} }
func (m *CreateGuestUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGuestUserRequest) ProtoMessage()    {}
func (*CreateGuestUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{4}
}

func (m *CreateGuestUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGuestUserRequest.Unmarshal(m, b)
}
func (m *CreateGuestUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGuestUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateGuestUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGuestUserRequest.Merge(m, src)
}
func (m *CreateGuestUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGuestUserRequest.Size(m)
}
func (m *CreateGuestUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGuestUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGuestUserRequest proto.InternalMessageInfo

func (m *CreateGuestUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateGuestUserRequest) GetScopeGroupings() []*ScopeGrouping {
	if m != nil {
		return m.ScopeGroupings
	}
	return nil
}

type CreateGuestUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGuestUserResponse) Reset()         { *m = CreateGuestUserResponse{} }
func (m *CreateGuestUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGuestUserResponse) ProtoMessage()    {}
func (*CreateGuestUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{5}
}

func (m *CreateGuestUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGuestUserResponse.Unmarshal(m, b)
}
func (m *CreateGuestUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGuestUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateGuestUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGuestUserResponse.Merge(m, src)
}
func (m *CreateGuestUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGuestUserResponse.Size(m)
}
func (m *CreateGuestUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGuestUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGuestUserResponse proto.InternalMessageInfo

func (m *CreateGuestUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateGuestUserResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CreateSessionRequest struct {
	Email                string           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string           `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ScopeGroupings       []*ScopeGrouping `protobuf:"bytes,3,rep,name=scope_groupings,json=scopeGroupings,proto3" json:"scope_groupings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateSessionRequest) Reset()         { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()    {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{6}
}

func (m *CreateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequest.Unmarshal(m, b)
}
func (m *CreateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequest.Merge(m, src)
}
func (m *CreateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequest.Size(m)
}
func (m *CreateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequest proto.InternalMessageInfo

func (m *CreateSessionRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateSessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateSessionRequest) GetScopeGroupings() []*ScopeGrouping {
	if m != nil {
		return m.ScopeGroupings
	}
	return nil
}

type CreateSessionResponse struct {
	Status               CreateSessionResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.CreateSessionResponse_Status" json:"status,omitempty"`
	Session              *Session                     `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateSessionResponse) Reset()         { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()    {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{7}
}

func (m *CreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponse.Unmarshal(m, b)
}
func (m *CreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponse.Merge(m, src)
}
func (m *CreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponse.Size(m)
}
func (m *CreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponse proto.InternalMessageInfo

func (m *CreateSessionResponse) GetStatus() CreateSessionResponse_Status {
	if m != nil {
		return m.Status
	}
	return CreateSessionResponse_SUCCESSFUL
}

func (m *CreateSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CreatePasswordResetTokenRequest struct {
	Email                string               `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatePasswordResetTokenRequest) Reset()         { *m = CreatePasswordResetTokenRequest{} }
func (m *CreatePasswordResetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResetTokenRequest) ProtoMessage()    {}
func (*CreatePasswordResetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{8}
}

func (m *CreatePasswordResetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResetTokenRequest.Unmarshal(m, b)
}
func (m *CreatePasswordResetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResetTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreatePasswordResetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResetTokenRequest.Merge(m, src)
}
func (m *CreatePasswordResetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResetTokenRequest.Size(m)
}
func (m *CreatePasswordResetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResetTokenRequest proto.InternalMessageInfo

func (m *CreatePasswordResetTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreatePasswordResetTokenRequest) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type CreatePasswordResetTokenResponse struct {
	PasswordResetToken   string   `protobuf:"bytes,1,opt,name=password_reset_token,json=passwordResetToken,proto3" json:"password_reset_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordResetTokenResponse) Reset()         { *m = CreatePasswordResetTokenResponse{} }
func (m *CreatePasswordResetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResetTokenResponse) ProtoMessage()    {}
func (*CreatePasswordResetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{9}
}

func (m *CreatePasswordResetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResetTokenResponse.Unmarshal(m, b)
}
func (m *CreatePasswordResetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResetTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreatePasswordResetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResetTokenResponse.Merge(m, src)
}
func (m *CreatePasswordResetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResetTokenResponse.Size(m)
}
func (m *CreatePasswordResetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResetTokenResponse proto.InternalMessageInfo

func (m *CreatePasswordResetTokenResponse) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

type ResetUserPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string   `protobuf:"bytes,3,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	PasswordResetToken   string   `protobuf:"bytes,4,opt,name=password_reset_token,json=passwordResetToken,proto3" json:"password_reset_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetUserPasswordRequest) Reset()         { *m = ResetUserPasswordRequest{} }
func (m *ResetUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetUserPasswordRequest) ProtoMessage()    {}
func (*ResetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{10}
}

func (m *ResetUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUserPasswordRequest.Unmarshal(m, b)
}
func (m *ResetUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUserPasswordRequest.Merge(m, src)
}
func (m *ResetUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetUserPasswordRequest.Size(m)
}
func (m *ResetUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUserPasswordRequest proto.InternalMessageInfo

func (m *ResetUserPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetUserPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetUserPasswordRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *ResetUserPasswordRequest) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

type ResetUserPasswordResponse struct {
	Status               ResetUserPasswordResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.ResetUserPasswordResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ResetUserPasswordResponse) Reset()         { *m = ResetUserPasswordResponse{} }
func (m *ResetUserPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetUserPasswordResponse) ProtoMessage()    {}
func (*ResetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{11}
}

func (m *ResetUserPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUserPasswordResponse.Unmarshal(m, b)
}
func (m *ResetUserPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUserPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetUserPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUserPasswordResponse.Merge(m, src)
}
func (m *ResetUserPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetUserPasswordResponse.Size(m)
}
func (m *ResetUserPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUserPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUserPasswordResponse proto.InternalMessageInfo

func (m *ResetUserPasswordResponse) GetStatus() ResetUserPasswordResponse_Status {
	if m != nil {
		return m.Status
	}
	return ResetUserPasswordResponse_SUCCESSFUL
}

type DeleteSessionRequest struct {
	// Types that are valid to be assigned to Representation:
	//	*DeleteSessionRequest_Uuid
	//	*DeleteSessionRequest_Token
	Representation       isDeleteSessionRequest_Representation `protobuf_oneof:"representation"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DeleteSessionRequest) Reset()         { *m = DeleteSessionRequest{} }
func (m *DeleteSessionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionRequest) ProtoMessage()    {}
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{12}
}

func (m *DeleteSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionRequest.Unmarshal(m, b)
}
func (m *DeleteSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionRequest.Merge(m, src)
}
func (m *DeleteSessionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionRequest.Size(m)
}
func (m *DeleteSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionRequest proto.InternalMessageInfo

type isDeleteSessionRequest_Representation interface {
	isDeleteSessionRequest_Representation()
}

type DeleteSessionRequest_Uuid struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type DeleteSessionRequest_Token struct {
	Token string `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

func (*DeleteSessionRequest_Uuid) isDeleteSessionRequest_Representation() {}

func (*DeleteSessionRequest_Token) isDeleteSessionRequest_Representation() {}

func (m *DeleteSessionRequest) GetRepresentation() isDeleteSessionRequest_Representation {
	if m != nil {
		return m.Representation
	}
	return nil
}

func (m *DeleteSessionRequest) GetUuid() string {
	if x, ok := m.GetRepresentation().(*DeleteSessionRequest_Uuid); ok {
		return x.Uuid
	}
	return ""
}

func (m *DeleteSessionRequest) GetToken() string {
	if x, ok := m.GetRepresentation().(*DeleteSessionRequest_Token); ok {
		return x.Token
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DeleteSessionRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DeleteSessionRequest_OneofMarshaler, _DeleteSessionRequest_OneofUnmarshaler, _DeleteSessionRequest_OneofSizer, []interface{}{
		(*DeleteSessionRequest_Uuid)(nil),
		(*DeleteSessionRequest_Token)(nil),
	}
}

func _DeleteSessionRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DeleteSessionRequest)
	// representation
	switch x := m.Representation.(type) {
	case *DeleteSessionRequest_Uuid:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Uuid)
	case *DeleteSessionRequest_Token:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Token)
	case nil:
	default:
		return fmt.Errorf("DeleteSessionRequest.Representation has unexpected type %T", x)
	}
	return nil
}

func _DeleteSessionRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DeleteSessionRequest)
	switch tag {
	case 1: // representation.uuid
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Representation = &DeleteSessionRequest_Uuid{x}
		return true, err
	case 2: // representation.token
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Representation = &DeleteSessionRequest_Token{x}
		return true, err
	default:
		return false, nil
	}
}

func _DeleteSessionRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DeleteSessionRequest)
	// representation
	switch x := m.Representation.(type) {
	case *DeleteSessionRequest_Uuid:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Uuid)))
		n += len(x.Uuid)
	case *DeleteSessionRequest_Token:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Token)))
		n += len(x.Token)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DeleteSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionResponse) Reset()         { *m = DeleteSessionResponse{} }
func (m *DeleteSessionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionResponse) ProtoMessage()    {}
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{13}
}

func (m *DeleteSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionResponse.Unmarshal(m, b)
}
func (m *DeleteSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionResponse.Merge(m, src)
}
func (m *DeleteSessionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionResponse.Size(m)
}
func (m *DeleteSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionResponse proto.InternalMessageInfo

type GetSessionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionRequest) Reset()         { *m = GetSessionRequest{} }
func (m *GetSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetSessionRequest) ProtoMessage()    {}
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{14}
}

func (m *GetSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionRequest.Unmarshal(m, b)
}
func (m *GetSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionRequest.Marshal(b, m, deterministic)
}
func (m *GetSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionRequest.Merge(m, src)
}
func (m *GetSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetSessionRequest.Size(m)
}
func (m *GetSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionRequest proto.InternalMessageInfo

func (m *GetSessionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetSessionResponse struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionResponse) Reset()         { *m = GetSessionResponse{} }
func (m *GetSessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetSessionResponse) ProtoMessage()    {}
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{15}
}

func (m *GetSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionResponse.Unmarshal(m, b)
}
func (m *GetSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionResponse.Marshal(b, m, deterministic)
}
func (m *GetSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionResponse.Merge(m, src)
}
func (m *GetSessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetSessionResponse.Size(m)
}
func (m *GetSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionResponse proto.InternalMessageInfo

func (m *GetSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type DeleteUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{16}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DeleteUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{17}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type User struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{18}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ScopeGrouping struct {
	Scopes               []string             `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ScopeGrouping) Reset()         { *m = ScopeGrouping{} }
func (m *ScopeGrouping) String() string { return proto.CompactTextString(m) }
func (*ScopeGrouping) ProtoMessage()    {}
func (*ScopeGrouping) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{19}
}

func (m *ScopeGrouping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopeGrouping.Unmarshal(m, b)
}
func (m *ScopeGrouping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopeGrouping.Marshal(b, m, deterministic)
}
func (m *ScopeGrouping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopeGrouping.Merge(m, src)
}
func (m *ScopeGrouping) XXX_Size() int {
	return xxx_messageInfo_ScopeGrouping.Size(m)
}
func (m *ScopeGrouping) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopeGrouping.DiscardUnknown(m)
}

var xxx_messageInfo_ScopeGrouping proto.InternalMessageInfo

func (m *ScopeGrouping) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *ScopeGrouping) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type Session struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Json                 string   `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{20}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Session) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.CreateSessionResponse_Status", CreateSessionResponse_Status_name, CreateSessionResponse_Status_value)
	proto.RegisterEnum("proto.ResetUserPasswordResponse_Status", ResetUserPasswordResponse_Status_name, ResetUserPasswordResponse_Status_value)
	proto.RegisterType((*GetUserRequest)(nil), "proto.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "proto.GetUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "proto.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "proto.CreateUserResponse")
	proto.RegisterType((*CreateGuestUserRequest)(nil), "proto.CreateGuestUserRequest")
	proto.RegisterType((*CreateGuestUserResponse)(nil), "proto.CreateGuestUserResponse")
	proto.RegisterType((*CreateSessionRequest)(nil), "proto.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "proto.CreateSessionResponse")
	proto.RegisterType((*CreatePasswordResetTokenRequest)(nil), "proto.CreatePasswordResetTokenRequest")
	proto.RegisterType((*CreatePasswordResetTokenResponse)(nil), "proto.CreatePasswordResetTokenResponse")
	proto.RegisterType((*ResetUserPasswordRequest)(nil), "proto.ResetUserPasswordRequest")
	proto.RegisterType((*ResetUserPasswordResponse)(nil), "proto.ResetUserPasswordResponse")
	proto.RegisterType((*DeleteSessionRequest)(nil), "proto.DeleteSessionRequest")
	proto.RegisterType((*DeleteSessionResponse)(nil), "proto.DeleteSessionResponse")
	proto.RegisterType((*GetSessionRequest)(nil), "proto.GetSessionRequest")
	proto.RegisterType((*GetSessionResponse)(nil), "proto.GetSessionResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "proto.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "proto.DeleteUserResponse")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*ScopeGrouping)(nil), "proto.ScopeGrouping")
	proto.RegisterType((*Session)(nil), "proto.Session")
}

func init() { proto.RegisterFile("fingerprint.proto", fileDescriptor_958480b1a11f31b5) }

var fileDescriptor_958480b1a11f31b5 = []byte{
	// 844 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdf, 0x72, 0xd2, 0x4e,
	0x14, 0x26, 0x40, 0xe9, 0xaf, 0xa7, 0xbf, 0x52, 0xd8, 0x01, 0x4a, 0xa9, 0x0a, 0xb3, 0xce, 0x58,
	0xbc, 0xa1, 0x1d, 0x7a, 0x57, 0x47, 0x9d, 0x96, 0x52, 0xda, 0x91, 0xfe, 0x99, 0x04, 0x74, 0xbc,
	0xca, 0x50, 0x58, 0x98, 0x68, 0x49, 0x62, 0x36, 0xa8, 0x6f, 0xe0, 0xbb, 0x78, 0xe3, 0x85, 0x57,
	0x3e, 0x8a, 0x6f, 0xe3, 0x64, 0x77, 0x13, 0x12, 0x48, 0x8a, 0x58, 0xc7, 0x2b, 0x38, 0x39, 0x27,
	0xe7, 0x7c, 0xe7, 0xdb, 0x3d, 0xdf, 0x09, 0x64, 0x87, 0x9a, 0x3e, 0x22, 0x96, 0x69, 0x69, 0xba,
	0x5d, 0x33, 0x2d, 0xc3, 0x36, 0xd0, 0x0a, 0xfb, 0x29, 0x95, 0x47, 0x86, 0x31, 0xba, 0x25, 0x7b,
	0xcc, 0xba, 0x99, 0x0c, 0xf7, 0x6c, 0x6d, 0x4c, 0xa8, 0xdd, 0x1b, 0x9b, 0x3c, 0x0e, 0xb7, 0x21,
	0xdd, 0x22, 0x76, 0x97, 0x12, 0x4b, 0x26, 0x1f, 0x26, 0x84, 0xda, 0x28, 0x07, 0xc9, 0xc9, 0x44,
	0x1b, 0x14, 0xa5, 0x8a, 0x54, 0x5d, 0x3b, 0x8b, 0xc9, 0xcc, 0x42, 0x05, 0x58, 0x21, 0xe3, 0x9e,
	0x76, 0x5b, 0x8c, 0x8b, 0xc7, 0xdc, 0x3c, 0xfe, 0x1f, 0x40, 0x1b, 0x10, 0xdd, 0xd6, 0x86, 0x1a,
	0xb1, 0x70, 0x1d, 0x36, 0xbd, 0x6c, 0xd4, 0x34, 0x74, 0x4a, 0x50, 0x19, 0x92, 0x13, 0x4a, 0x2c,
	0x96, 0x6e, 0xbd, 0xbe, 0xce, 0xcb, 0xd6, 0x58, 0x08, 0x73, 0xe0, 0x1f, 0x12, 0x64, 0x1b, 0x16,
	0xe9, 0xd9, 0x24, 0x88, 0x42, 0xd4, 0x63, 0x30, 0x44, 0x35, 0x54, 0x82, 0xff, 0xcc, 0x1e, 0xa5,
	0x9f, 0x0c, 0x6b, 0xc0, 0x81, 0xc8, 0x9e, 0x8d, 0x0e, 0x20, 0xef, 0xfe, 0x57, 0xfb, 0x86, 0x3e,
	0xd4, 0xac, 0x71, 0xcf, 0xd6, 0x0c, 0xbd, 0x98, 0x60, 0x81, 0x39, 0xd7, 0xd9, 0xf0, 0xf9, 0xd0,
	0x73, 0xd8, 0xa4, 0x7d, 0xc3, 0x24, 0xea, 0xc8, 0x32, 0x26, 0xa6, 0xa6, 0x8f, 0x68, 0x31, 0x59,
	0x49, 0x54, 0xd7, 0xeb, 0x39, 0x01, 0x54, 0x71, 0xbc, 0x2d, 0xe1, 0x94, 0xd3, 0xd4, 0x6f, 0x52,
	0xac, 0x02, 0xf2, 0x43, 0xff, 0xcd, 0x96, 0x51, 0x15, 0x56, 0x29, 0xa1, 0xd4, 0x01, 0x17, 0x67,
	0x31, 0x69, 0xb7, 0x1a, 0x7f, 0x2a, 0xbb, 0x6e, 0x3c, 0x86, 0x02, 0x2f, 0xd0, 0x72, 0x58, 0x59,
	0x4c, 0x50, 0x48, 0x3f, 0xf1, 0x25, 0xfa, 0x19, 0xc0, 0xd6, 0x5c, 0xb9, 0xbf, 0xdf, 0xd4, 0x17,
	0x09, 0x72, 0xbc, 0x8c, 0xeb, 0xfa, 0xe3, 0x43, 0x0f, 0xe9, 0x37, 0xb1, 0x44, 0xbf, 0xdf, 0x24,
	0xc8, 0xcf, 0x20, 0x11, 0xed, 0x3e, 0x83, 0x14, 0xb5, 0x7b, 0xf6, 0x84, 0x32, 0x2c, 0xe9, 0xfa,
	0x63, 0x91, 0x2f, 0x34, 0xba, 0xa6, 0xb0, 0x50, 0x59, 0xbc, 0xb2, 0x04, 0x15, 0x7b, 0x90, 0xe2,
	0xef, 0xa2, 0x34, 0x80, 0xd2, 0x6d, 0x34, 0x9a, 0x8a, 0x72, 0xda, 0x6d, 0x67, 0x62, 0x28, 0x0f,
	0xd9, 0xeb, 0x23, 0x45, 0x79, 0x73, 0x25, 0x9f, 0xa8, 0x17, 0xe7, 0xca, 0xc5, 0x51, 0xa7, 0x71,
	0x96, 0x91, 0x30, 0x85, 0x32, 0x87, 0x70, 0x2d, 0x28, 0x90, 0x09, 0x25, 0x76, 0xc7, 0x78, 0x4f,
	0x16, 0xb0, 0x78, 0x08, 0x40, 0x3e, 0x9b, 0x9a, 0xc5, 0x67, 0x82, 0xc3, 0x2a, 0xd5, 0xb8, 0x3c,
	0xd4, 0x5c, 0x79, 0xa8, 0x75, 0x5c, 0x79, 0x90, 0x7d, 0xd1, 0xb8, 0x03, 0x95, 0xe8, 0xa2, 0x82,
	0xb0, 0x7d, 0xf0, 0x26, 0x4c, 0xb5, 0x1c, 0xb7, 0x6a, 0x3b, 0x7e, 0x01, 0x02, 0x99, 0x73, 0x6f,
	0xe2, 0xef, 0x12, 0x14, 0x99, 0xe9, 0x5c, 0xa2, 0x69, 0xe6, 0x7f, 0x3a, 0xff, 0x51, 0xa8, 0x93,
	0x91, 0xa8, 0xbf, 0x4a, 0xb0, 0x1d, 0x82, 0x5a, 0xb0, 0xf0, 0x72, 0xe6, 0xda, 0xec, 0x8a, 0x83,
	0x8f, 0x7c, 0x63, 0xe6, 0xea, 0xe0, 0xf6, 0x92, 0x17, 0x02, 0xed, 0xc0, 0xd6, 0xe5, 0x95, 0xca,
	0xac, 0xf3, 0xcb, 0x96, 0x2a, 0x37, 0x95, 0x66, 0x47, 0xed, 0x5c, 0xbd, 0x6a, 0x5e, 0x66, 0xe2,
	0xf8, 0x35, 0xe4, 0x4e, 0xc8, 0x2d, 0x09, 0x19, 0xb4, 0x08, 0x8d, 0xe7, 0xdd, 0x7b, 0x1a, 0xcf,
	0xcc, 0xe3, 0x0c, 0xa4, 0x2d, 0x62, 0x3a, 0xf4, 0xe8, 0x36, 0xbf, 0x10, 0x5b, 0x90, 0x9f, 0xc9,
	0xcb, 0xbb, 0xc1, 0x4f, 0x21, 0xdb, 0x22, 0xf6, 0xfc, 0x58, 0xfb, 0xef, 0x02, 0x37, 0xf0, 0x0b,
	0x40, 0xfe, 0x50, 0x41, 0xa0, 0x6f, 0x74, 0xa4, 0xbb, 0x47, 0xa7, 0x09, 0x59, 0x8e, 0xe1, 0x5e,
	0x6b, 0x03, 0xe7, 0x00, 0xf9, 0xd3, 0x88, 0x3e, 0xf6, 0x21, 0xe9, 0xd8, 0x08, 0xf9, 0x89, 0x12,
	0x34, 0xe5, 0x02, 0xab, 0x50, 0xd4, 0xc0, 0x7d, 0xd8, 0x08, 0x68, 0x0d, 0x2a, 0x40, 0x8a, 0xa9,
	0x8d, 0x73, 0x15, 0x12, 0xd5, 0x35, 0x59, 0x58, 0xf7, 0x1a, 0xc4, 0x16, 0xac, 0x0a, 0x1e, 0xa2,
	0x90, 0xf9, 0x0e, 0x50, 0x10, 0xed, 0x44, 0xbe, 0xa3, 0xde, 0x1c, 0xb0, 0xff, 0xf5, 0x9f, 0x2b,
	0x80, 0x4e, 0xa7, 0x1f, 0x0d, 0x0a, 0xb1, 0x3e, 0x6a, 0x7d, 0x82, 0x0e, 0x61, 0x55, 0xec, 0x6f,
	0x94, 0x17, 0xbc, 0x07, 0xbf, 0x0e, 0x4a, 0x85, 0xd9, 0xc7, 0x82, 0xb0, 0x18, 0x6a, 0x00, 0x4c,
	0x77, 0x21, 0x2a, 0x06, 0xf4, 0xd2, 0x9f, 0x61, 0x3b, 0xc4, 0xe3, 0x25, 0x91, 0x61, 0x73, 0x66,
	0x01, 0xa1, 0x87, 0x81, 0xf8, 0xd9, 0x3d, 0x58, 0x7a, 0x14, 0xe5, 0xf6, 0x03, 0x9b, 0x9e, 0xb0,
	0x07, 0x6c, 0xee, 0xee, 0x78, 0xc0, 0x42, 0xae, 0x43, 0x0c, 0x8d, 0xa1, 0x18, 0x25, 0x81, 0xe8,
	0x49, 0x00, 0x42, 0xa4, 0x30, 0x97, 0x76, 0x17, 0xc6, 0x79, 0xe5, 0xde, 0x02, 0xea, 0x9a, 0x03,
	0xc1, 0x8f, 0x1b, 0x89, 0xca, 0xd1, 0x6a, 0xc2, 0x2b, 0x54, 0x16, 0xc9, 0x0d, 0x8e, 0xa1, 0x36,
	0x6c, 0x04, 0x96, 0x18, 0xda, 0x09, 0x5f, 0x6d, 0x3c, 0xe3, 0x83, 0xbb, 0xf6, 0x1e, 0xcf, 0x16,
	0x50, 0x02, 0x2f, 0x5b, 0x98, 0xee, 0x78, 0xd9, 0xc2, 0xc5, 0x83, 0x1d, 0xd5, 0x54, 0x13, 0xbc,
	0xa3, 0x9a, 0x53, 0x14, 0xef, 0xa8, 0xe6, 0x05, 0x04, 0xc7, 0x6e, 0x52, 0xcc, 0x77, 0xf0, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0x19, 0x85, 0x79, 0x6a, 0x16, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FingerprintServiceClient is the client API for FingerprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FingerprintServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	CreateGuestUser(ctx context.Context, in *CreateGuestUserRequest, opts ...grpc.CallOption) (*CreateGuestUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	CreatePasswordResetToken(ctx context.Context, in *CreatePasswordResetTokenRequest, opts ...grpc.CallOption) (*CreatePasswordResetTokenResponse, error)
	UpdateUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*ResetUserPasswordResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
}

type fingerprintServiceClient struct {
	cc *grpc.ClientConn
}

func NewFingerprintServiceClient(cc *grpc.ClientConn) FingerprintServiceClient {
	return &fingerprintServiceClient{cc}
}

func (c *fingerprintServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreateGuestUser(ctx context.Context, in *CreateGuestUserRequest, opts ...grpc.CallOption) (*CreateGuestUserResponse, error) {
	out := new(CreateGuestUserResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreateGuestUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreatePasswordResetToken(ctx context.Context, in *CreatePasswordResetTokenRequest, opts ...grpc.CallOption) (*CreatePasswordResetTokenResponse, error) {
	out := new(CreatePasswordResetTokenResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreatePasswordResetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) UpdateUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*ResetUserPasswordResponse, error) {
	out := new(ResetUserPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/UpdateUserPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/DeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/GetSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FingerprintServiceServer is the server API for FingerprintService service.
type FingerprintServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	CreateGuestUser(context.Context, *CreateGuestUserRequest) (*CreateGuestUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	CreatePasswordResetToken(context.Context, *CreatePasswordResetTokenRequest) (*CreatePasswordResetTokenResponse, error)
	UpdateUserPassword(context.Context, *ResetUserPasswordRequest) (*ResetUserPasswordResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
}

func RegisterFingerprintServiceServer(s *grpc.Server, srv FingerprintServiceServer) {
	s.RegisterService(&_FingerprintService_serviceDesc, srv)
}

func _FingerprintService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreateGuestUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuestUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreateGuestUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreateGuestUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreateGuestUser(ctx, req.(*CreateGuestUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreatePasswordResetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePasswordResetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreatePasswordResetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreatePasswordResetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreatePasswordResetToken(ctx, req.(*CreatePasswordResetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/UpdateUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).UpdateUserPassword(ctx, req.(*ResetUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FingerprintService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FingerprintService",
	HandlerType: (*FingerprintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _FingerprintService_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _FingerprintService_CreateUser_Handler,
		},
		{
			MethodName: "CreateGuestUser",
			Handler:    _FingerprintService_CreateGuestUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _FingerprintService_DeleteUser_Handler,
		},
		{
			MethodName: "CreatePasswordResetToken",
			Handler:    _FingerprintService_CreatePasswordResetToken_Handler,
		},
		{
			MethodName: "UpdateUserPassword",
			Handler:    _FingerprintService_UpdateUserPassword_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _FingerprintService_CreateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _FingerprintService_DeleteSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _FingerprintService_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fingerprint.proto",
}
