// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fingerprint.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResetUserPasswordResponse_Status int32

const (
	ResetUserPasswordResponse_SUCCESSFUL              ResetUserPasswordResponse_Status = 0
	ResetUserPasswordResponse_PASSWORD_MISMATCH       ResetUserPasswordResponse_Status = 1
	ResetUserPasswordResponse_NO_MATCHING_RESET_TOKEN ResetUserPasswordResponse_Status = 2
)

var ResetUserPasswordResponse_Status_name = map[int32]string{
	0: "SUCCESSFUL",
	1: "PASSWORD_MISMATCH",
	2: "NO_MATCHING_RESET_TOKEN",
}

var ResetUserPasswordResponse_Status_value = map[string]int32{
	"SUCCESSFUL":              0,
	"PASSWORD_MISMATCH":       1,
	"NO_MATCHING_RESET_TOKEN": 2,
}

func (x ResetUserPasswordResponse_Status) String() string {
	return proto.EnumName(ResetUserPasswordResponse_Status_name, int32(x))
}

func (ResetUserPasswordResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{11, 0}
}

type CreateSessionRevokeResponse_Status int32

const (
	CreateSessionRevokeResponse_REVOKED_UUID     CreateSessionRevokeResponse_Status = 0
	CreateSessionRevokeResponse_REVOKED_TOKEN    CreateSessionRevokeResponse_Status = 1
	CreateSessionRevokeResponse_NO_SESSION_FOUND CreateSessionRevokeResponse_Status = 3
)

var CreateSessionRevokeResponse_Status_name = map[int32]string{
	0: "REVOKED_UUID",
	1: "REVOKED_TOKEN",
	3: "NO_SESSION_FOUND",
}

var CreateSessionRevokeResponse_Status_value = map[string]int32{
	"REVOKED_UUID":     0,
	"REVOKED_TOKEN":    1,
	"NO_SESSION_FOUND": 3,
}

func (x CreateSessionRevokeResponse_Status) String() string {
	return proto.EnumName(CreateSessionRevokeResponse_Status_name, int32(x))
}

func (CreateSessionRevokeResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{13, 0}
}

type GetUserRequest struct {
	// Types that are valid to be assigned to Identifier:
	//	*GetUserRequest_Uuid
	//	*GetUserRequest_Email
	Identifier           isGetUserRequest_Identifier `protobuf_oneof:"identifier"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

type isGetUserRequest_Identifier interface {
	isGetUserRequest_Identifier()
}

type GetUserRequest_Uuid struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type GetUserRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*GetUserRequest_Uuid) isGetUserRequest_Identifier() {}

func (*GetUserRequest_Email) isGetUserRequest_Identifier() {}

func (m *GetUserRequest) GetIdentifier() isGetUserRequest_Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *GetUserRequest) GetUuid() string {
	if x, ok := m.GetIdentifier().(*GetUserRequest_Uuid); ok {
		return x.Uuid
	}
	return ""
}

func (m *GetUserRequest) GetEmail() string {
	if x, ok := m.GetIdentifier().(*GetUserRequest_Email); ok {
		return x.Email
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetUserRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetUserRequest_OneofMarshaler, _GetUserRequest_OneofUnmarshaler, _GetUserRequest_OneofSizer, []interface{}{
		(*GetUserRequest_Uuid)(nil),
		(*GetUserRequest_Email)(nil),
	}
}

func _GetUserRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetUserRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *GetUserRequest_Uuid:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Uuid)
	case *GetUserRequest_Email:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Email)
	case nil:
	default:
		return fmt.Errorf("GetUserRequest.Identifier has unexpected type %T", x)
	}
	return nil
}

func _GetUserRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetUserRequest)
	switch tag {
	case 1: // identifier.uuid
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &GetUserRequest_Uuid{x}
		return true, err
	case 2: // identifier.email
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &GetUserRequest_Email{x}
		return true, err
	default:
		return false, nil
	}
}

func _GetUserRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetUserRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *GetUserRequest_Uuid:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Uuid)))
		n += len(x.Uuid)
	case *GetUserRequest_Email:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Email)))
		n += len(x.Email)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserRequest struct {
	Email                string           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string           `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string           `protobuf:"bytes,3,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	ScopeGroupings       []*ScopeGrouping `protobuf:"bytes,4,rep,name=scope_groupings,json=scopeGroupings,proto3" json:"scope_groupings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *CreateUserRequest) GetScopeGroupings() []*ScopeGrouping {
	if m != nil {
		return m.ScopeGroupings
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{3}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CreateGuestUserRequest struct {
	Email                string           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ScopeGroupings       []*ScopeGrouping `protobuf:"bytes,2,rep,name=scope_groupings,json=scopeGroupings,proto3" json:"scope_groupings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateGuestUserRequest) Reset()         { *m = CreateGuestUserRequest{} }
func (m *CreateGuestUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGuestUserRequest) ProtoMessage()    {}
func (*CreateGuestUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{4}
}

func (m *CreateGuestUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGuestUserRequest.Unmarshal(m, b)
}
func (m *CreateGuestUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGuestUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateGuestUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGuestUserRequest.Merge(m, src)
}
func (m *CreateGuestUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGuestUserRequest.Size(m)
}
func (m *CreateGuestUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGuestUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGuestUserRequest proto.InternalMessageInfo

func (m *CreateGuestUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateGuestUserRequest) GetScopeGroupings() []*ScopeGrouping {
	if m != nil {
		return m.ScopeGroupings
	}
	return nil
}

type CreateGuestUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGuestUserResponse) Reset()         { *m = CreateGuestUserResponse{} }
func (m *CreateGuestUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGuestUserResponse) ProtoMessage()    {}
func (*CreateGuestUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{5}
}

func (m *CreateGuestUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGuestUserResponse.Unmarshal(m, b)
}
func (m *CreateGuestUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGuestUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateGuestUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGuestUserResponse.Merge(m, src)
}
func (m *CreateGuestUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGuestUserResponse.Size(m)
}
func (m *CreateGuestUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGuestUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGuestUserResponse proto.InternalMessageInfo

func (m *CreateGuestUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateGuestUserResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CreateSessionRequest struct {
	Email                string           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string           `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ScopeGroupings       []*ScopeGrouping `protobuf:"bytes,3,rep,name=scope_groupings,json=scopeGroupings,proto3" json:"scope_groupings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateSessionRequest) Reset()         { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()    {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{6}
}

func (m *CreateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequest.Unmarshal(m, b)
}
func (m *CreateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequest.Merge(m, src)
}
func (m *CreateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequest.Size(m)
}
func (m *CreateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequest proto.InternalMessageInfo

func (m *CreateSessionRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateSessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateSessionRequest) GetScopeGroupings() []*ScopeGrouping {
	if m != nil {
		return m.ScopeGroupings
	}
	return nil
}

type CreateSessionResponse struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionResponse) Reset()         { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()    {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{7}
}

func (m *CreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponse.Unmarshal(m, b)
}
func (m *CreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponse.Merge(m, src)
}
func (m *CreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponse.Size(m)
}
func (m *CreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponse proto.InternalMessageInfo

func (m *CreateSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CreatePasswordResetTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordResetTokenRequest) Reset()         { *m = CreatePasswordResetTokenRequest{} }
func (m *CreatePasswordResetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResetTokenRequest) ProtoMessage()    {}
func (*CreatePasswordResetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{8}
}

func (m *CreatePasswordResetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResetTokenRequest.Unmarshal(m, b)
}
func (m *CreatePasswordResetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResetTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreatePasswordResetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResetTokenRequest.Merge(m, src)
}
func (m *CreatePasswordResetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResetTokenRequest.Size(m)
}
func (m *CreatePasswordResetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResetTokenRequest proto.InternalMessageInfo

func (m *CreatePasswordResetTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreatePasswordResetTokenResponse struct {
	PasswordResetToken   string   `protobuf:"bytes,1,opt,name=password_reset_token,json=passwordResetToken,proto3" json:"password_reset_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordResetTokenResponse) Reset()         { *m = CreatePasswordResetTokenResponse{} }
func (m *CreatePasswordResetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResetTokenResponse) ProtoMessage()    {}
func (*CreatePasswordResetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{9}
}

func (m *CreatePasswordResetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResetTokenResponse.Unmarshal(m, b)
}
func (m *CreatePasswordResetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResetTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreatePasswordResetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResetTokenResponse.Merge(m, src)
}
func (m *CreatePasswordResetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResetTokenResponse.Size(m)
}
func (m *CreatePasswordResetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResetTokenResponse proto.InternalMessageInfo

func (m *CreatePasswordResetTokenResponse) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

type ResetUserPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string   `protobuf:"bytes,3,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	PasswordResetToken   string   `protobuf:"bytes,4,opt,name=password_reset_token,json=passwordResetToken,proto3" json:"password_reset_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetUserPasswordRequest) Reset()         { *m = ResetUserPasswordRequest{} }
func (m *ResetUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetUserPasswordRequest) ProtoMessage()    {}
func (*ResetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{10}
}

func (m *ResetUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUserPasswordRequest.Unmarshal(m, b)
}
func (m *ResetUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUserPasswordRequest.Merge(m, src)
}
func (m *ResetUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetUserPasswordRequest.Size(m)
}
func (m *ResetUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUserPasswordRequest proto.InternalMessageInfo

func (m *ResetUserPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetUserPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetUserPasswordRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

func (m *ResetUserPasswordRequest) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

type ResetUserPasswordResponse struct {
	Status               ResetUserPasswordResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.ResetUserPasswordResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ResetUserPasswordResponse) Reset()         { *m = ResetUserPasswordResponse{} }
func (m *ResetUserPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetUserPasswordResponse) ProtoMessage()    {}
func (*ResetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{11}
}

func (m *ResetUserPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUserPasswordResponse.Unmarshal(m, b)
}
func (m *ResetUserPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUserPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetUserPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUserPasswordResponse.Merge(m, src)
}
func (m *ResetUserPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetUserPasswordResponse.Size(m)
}
func (m *ResetUserPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUserPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUserPasswordResponse proto.InternalMessageInfo

func (m *ResetUserPasswordResponse) GetStatus() ResetUserPasswordResponse_Status {
	if m != nil {
		return m.Status
	}
	return ResetUserPasswordResponse_SUCCESSFUL
}

type CreateSessionRevokeRequest struct {
	// Types that are valid to be assigned to Revoke:
	//	*CreateSessionRevokeRequest_Uuid
	//	*CreateSessionRevokeRequest_Token
	Revoke               isCreateSessionRevokeRequest_Revoke `protobuf_oneof:"revoke"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *CreateSessionRevokeRequest) Reset()         { *m = CreateSessionRevokeRequest{} }
func (m *CreateSessionRevokeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRevokeRequest) ProtoMessage()    {}
func (*CreateSessionRevokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{12}
}

func (m *CreateSessionRevokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRevokeRequest.Unmarshal(m, b)
}
func (m *CreateSessionRevokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRevokeRequest.Marshal(b, m, deterministic)
}
func (m *CreateSessionRevokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRevokeRequest.Merge(m, src)
}
func (m *CreateSessionRevokeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRevokeRequest.Size(m)
}
func (m *CreateSessionRevokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRevokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRevokeRequest proto.InternalMessageInfo

type isCreateSessionRevokeRequest_Revoke interface {
	isCreateSessionRevokeRequest_Revoke()
}

type CreateSessionRevokeRequest_Uuid struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type CreateSessionRevokeRequest_Token struct {
	Token string `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

func (*CreateSessionRevokeRequest_Uuid) isCreateSessionRevokeRequest_Revoke() {}

func (*CreateSessionRevokeRequest_Token) isCreateSessionRevokeRequest_Revoke() {}

func (m *CreateSessionRevokeRequest) GetRevoke() isCreateSessionRevokeRequest_Revoke {
	if m != nil {
		return m.Revoke
	}
	return nil
}

func (m *CreateSessionRevokeRequest) GetUuid() string {
	if x, ok := m.GetRevoke().(*CreateSessionRevokeRequest_Uuid); ok {
		return x.Uuid
	}
	return ""
}

func (m *CreateSessionRevokeRequest) GetToken() string {
	if x, ok := m.GetRevoke().(*CreateSessionRevokeRequest_Token); ok {
		return x.Token
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateSessionRevokeRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateSessionRevokeRequest_OneofMarshaler, _CreateSessionRevokeRequest_OneofUnmarshaler, _CreateSessionRevokeRequest_OneofSizer, []interface{}{
		(*CreateSessionRevokeRequest_Uuid)(nil),
		(*CreateSessionRevokeRequest_Token)(nil),
	}
}

func _CreateSessionRevokeRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateSessionRevokeRequest)
	// revoke
	switch x := m.Revoke.(type) {
	case *CreateSessionRevokeRequest_Uuid:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Uuid)
	case *CreateSessionRevokeRequest_Token:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Token)
	case nil:
	default:
		return fmt.Errorf("CreateSessionRevokeRequest.Revoke has unexpected type %T", x)
	}
	return nil
}

func _CreateSessionRevokeRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateSessionRevokeRequest)
	switch tag {
	case 1: // revoke.uuid
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Revoke = &CreateSessionRevokeRequest_Uuid{x}
		return true, err
	case 2: // revoke.token
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Revoke = &CreateSessionRevokeRequest_Token{x}
		return true, err
	default:
		return false, nil
	}
}

func _CreateSessionRevokeRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateSessionRevokeRequest)
	// revoke
	switch x := m.Revoke.(type) {
	case *CreateSessionRevokeRequest_Uuid:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Uuid)))
		n += len(x.Uuid)
	case *CreateSessionRevokeRequest_Token:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Token)))
		n += len(x.Token)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateSessionRevokeResponse struct {
	Status               CreateSessionRevokeResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.CreateSessionRevokeResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *CreateSessionRevokeResponse) Reset()         { *m = CreateSessionRevokeResponse{} }
func (m *CreateSessionRevokeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRevokeResponse) ProtoMessage()    {}
func (*CreateSessionRevokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{13}
}

func (m *CreateSessionRevokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRevokeResponse.Unmarshal(m, b)
}
func (m *CreateSessionRevokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRevokeResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionRevokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRevokeResponse.Merge(m, src)
}
func (m *CreateSessionRevokeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRevokeResponse.Size(m)
}
func (m *CreateSessionRevokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRevokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRevokeResponse proto.InternalMessageInfo

func (m *CreateSessionRevokeResponse) GetStatus() CreateSessionRevokeResponse_Status {
	if m != nil {
		return m.Status
	}
	return CreateSessionRevokeResponse_REVOKED_UUID
}

type GetSessionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionRequest) Reset()         { *m = GetSessionRequest{} }
func (m *GetSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetSessionRequest) ProtoMessage()    {}
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{14}
}

func (m *GetSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionRequest.Unmarshal(m, b)
}
func (m *GetSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionRequest.Marshal(b, m, deterministic)
}
func (m *GetSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionRequest.Merge(m, src)
}
func (m *GetSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetSessionRequest.Size(m)
}
func (m *GetSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionRequest proto.InternalMessageInfo

func (m *GetSessionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetSessionResponse struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionResponse) Reset()         { *m = GetSessionResponse{} }
func (m *GetSessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetSessionResponse) ProtoMessage()    {}
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{15}
}

func (m *GetSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionResponse.Unmarshal(m, b)
}
func (m *GetSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionResponse.Marshal(b, m, deterministic)
}
func (m *GetSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionResponse.Merge(m, src)
}
func (m *GetSessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetSessionResponse.Size(m)
}
func (m *GetSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionResponse proto.InternalMessageInfo

func (m *GetSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type User struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{16}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ScopeGrouping struct {
	Scopes               []string             `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ScopeGrouping) Reset()         { *m = ScopeGrouping{} }
func (m *ScopeGrouping) String() string { return proto.CompactTextString(m) }
func (*ScopeGrouping) ProtoMessage()    {}
func (*ScopeGrouping) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{17}
}

func (m *ScopeGrouping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopeGrouping.Unmarshal(m, b)
}
func (m *ScopeGrouping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopeGrouping.Marshal(b, m, deterministic)
}
func (m *ScopeGrouping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopeGrouping.Merge(m, src)
}
func (m *ScopeGrouping) XXX_Size() int {
	return xxx_messageInfo_ScopeGrouping.Size(m)
}
func (m *ScopeGrouping) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopeGrouping.DiscardUnknown(m)
}

var xxx_messageInfo_ScopeGrouping proto.InternalMessageInfo

func (m *ScopeGrouping) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *ScopeGrouping) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type Session struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Json                 string   `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_958480b1a11f31b5, []int{18}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Session) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.ResetUserPasswordResponse_Status", ResetUserPasswordResponse_Status_name, ResetUserPasswordResponse_Status_value)
	proto.RegisterEnum("proto.CreateSessionRevokeResponse_Status", CreateSessionRevokeResponse_Status_name, CreateSessionRevokeResponse_Status_value)
	proto.RegisterType((*GetUserRequest)(nil), "proto.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "proto.GetUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "proto.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "proto.CreateUserResponse")
	proto.RegisterType((*CreateGuestUserRequest)(nil), "proto.CreateGuestUserRequest")
	proto.RegisterType((*CreateGuestUserResponse)(nil), "proto.CreateGuestUserResponse")
	proto.RegisterType((*CreateSessionRequest)(nil), "proto.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "proto.CreateSessionResponse")
	proto.RegisterType((*CreatePasswordResetTokenRequest)(nil), "proto.CreatePasswordResetTokenRequest")
	proto.RegisterType((*CreatePasswordResetTokenResponse)(nil), "proto.CreatePasswordResetTokenResponse")
	proto.RegisterType((*ResetUserPasswordRequest)(nil), "proto.ResetUserPasswordRequest")
	proto.RegisterType((*ResetUserPasswordResponse)(nil), "proto.ResetUserPasswordResponse")
	proto.RegisterType((*CreateSessionRevokeRequest)(nil), "proto.CreateSessionRevokeRequest")
	proto.RegisterType((*CreateSessionRevokeResponse)(nil), "proto.CreateSessionRevokeResponse")
	proto.RegisterType((*GetSessionRequest)(nil), "proto.GetSessionRequest")
	proto.RegisterType((*GetSessionResponse)(nil), "proto.GetSessionResponse")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*ScopeGrouping)(nil), "proto.ScopeGrouping")
	proto.RegisterType((*Session)(nil), "proto.Session")
}

func init() { proto.RegisterFile("fingerprint.proto", fileDescriptor_958480b1a11f31b5) }

var fileDescriptor_958480b1a11f31b5 = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5f, 0x8f, 0xda, 0x46,
	0x10, 0xc7, 0xc0, 0x71, 0xc9, 0x5c, 0x8e, 0x83, 0x29, 0x10, 0xc2, 0xb5, 0x85, 0xee, 0x4b, 0xc8,
	0x0b, 0x89, 0xc8, 0x43, 0xa5, 0x48, 0x6d, 0x45, 0x80, 0x23, 0x28, 0x04, 0x22, 0x1b, 0x5a, 0xf5,
	0xa5, 0x16, 0x81, 0x05, 0xb9, 0x09, 0xb6, 0xeb, 0x35, 0x69, 0xbf, 0x41, 0x3f, 0x49, 0x55, 0xa9,
	0xaf, 0x7d, 0xea, 0xb7, 0xab, 0xbc, 0xbb, 0x36, 0x36, 0xd8, 0x70, 0x57, 0x55, 0x79, 0xb2, 0x67,
	0x67, 0x76, 0xe6, 0x37, 0xbf, 0x9d, 0x3f, 0x50, 0x5c, 0x19, 0xe6, 0x9a, 0x3a, 0xb6, 0x63, 0x98,
	0x6e, 0xcb, 0x76, 0x2c, 0xd7, 0xc2, 0x33, 0xfe, 0xa9, 0xd5, 0xd7, 0x96, 0xb5, 0xfe, 0x40, 0x9f,
	0x72, 0xe9, 0xdd, 0x76, 0xf5, 0xd4, 0x35, 0x36, 0x94, 0xb9, 0xf3, 0x8d, 0x2d, 0xec, 0xc8, 0x08,
	0xf2, 0x03, 0xea, 0xce, 0x18, 0x75, 0x54, 0xfa, 0xcb, 0x96, 0x32, 0x17, 0x4b, 0x90, 0xdd, 0x6e,
	0x8d, 0x65, 0x55, 0x69, 0x28, 0xcd, 0xfb, 0xaf, 0x52, 0x2a, 0x97, 0xb0, 0x02, 0x67, 0x74, 0x33,
	0x37, 0x3e, 0x54, 0xd3, 0xf2, 0x58, 0x88, 0x2f, 0x1f, 0x00, 0x18, 0x4b, 0x6a, 0xba, 0xc6, 0xca,
	0xa0, 0x0e, 0x69, 0xc3, 0x55, 0xe0, 0x8d, 0xd9, 0x96, 0xc9, 0x28, 0xd6, 0x21, 0xbb, 0x65, 0xd4,
	0xe1, 0xee, 0x2e, 0xda, 0x17, 0x22, 0x6c, 0x8b, 0x9b, 0x70, 0x05, 0xf9, 0x47, 0x81, 0x62, 0xd7,
	0xa1, 0x73, 0x97, 0x46, 0x51, 0xc8, 0x78, 0x1c, 0x86, 0x8c, 0x86, 0x35, 0xb8, 0x67, 0xcf, 0x19,
	0xfb, 0xd5, 0x72, 0x96, 0x02, 0x88, 0x1a, 0xc8, 0xf8, 0x1c, 0xca, 0xfe, 0xbf, 0xbe, 0xb0, 0xcc,
	0x95, 0xe1, 0x6c, 0xe6, 0xae, 0x61, 0x99, 0xd5, 0x0c, 0x37, 0x2c, 0xf9, 0xca, 0x6e, 0x48, 0x87,
	0xdf, 0xc0, 0x15, 0x5b, 0x58, 0x36, 0xd5, 0xd7, 0x8e, 0xb5, 0xb5, 0x0d, 0x73, 0xcd, 0xaa, 0xd9,
	0x46, 0xa6, 0x79, 0xd1, 0x2e, 0x49, 0xa0, 0x9a, 0xa7, 0x1d, 0x48, 0xa5, 0x9a, 0x67, 0x61, 0x91,
	0x11, 0x1d, 0x30, 0x0c, 0xfd, 0x96, 0x29, 0x63, 0x13, 0xce, 0x19, 0x65, 0xcc, 0x03, 0x97, 0xe6,
	0x36, 0x79, 0x3f, 0x9a, 0x38, 0x55, 0x7d, 0x35, 0xd9, 0x40, 0x45, 0x04, 0x18, 0x78, 0xac, 0x9c,
	0x26, 0x28, 0x26, 0x9f, 0xf4, 0x1d, 0xf2, 0x59, 0xc2, 0xc3, 0x83, 0x70, 0xff, 0x7f, 0x52, 0xbf,
	0x2b, 0x50, 0x12, 0x61, 0x7c, 0xd5, 0x7f, 0x7e, 0xf4, 0x98, 0x7c, 0x33, 0x77, 0xc8, 0xb7, 0x03,
	0xe5, 0x3d, 0x20, 0x32, 0xdb, 0x50, 0x32, 0xca, 0xf1, 0x64, 0xbe, 0x86, 0xba, 0x70, 0xf1, 0x56,
	0x62, 0x52, 0x29, 0xa3, 0xee, 0xd4, 0x7a, 0x4f, 0x8f, 0xa7, 0x45, 0xa6, 0xd0, 0x48, 0xbe, 0x28,
	0x61, 0x3c, 0x83, 0xa0, 0x6c, 0x75, 0xc7, 0x53, 0xeb, 0xae, 0xa7, 0x97, 0x8e, 0xd0, 0x3e, 0xb8,
	0x49, 0xfe, 0x56, 0xa0, 0xca, 0x45, 0xef, 0x65, 0x76, 0x9e, 0x3f, 0x69, 0x53, 0x25, 0xa1, 0xce,
	0x26, 0xa2, 0xfe, 0x4b, 0x81, 0x47, 0x31, 0xa8, 0x25, 0x0b, 0xdf, 0x41, 0x8e, 0xb9, 0x73, 0x77,
	0xcb, 0x38, 0xee, 0x7c, 0xfb, 0xb1, 0x7c, 0x8b, 0xc4, 0x1b, 0x2d, 0x8d, 0x9b, 0xab, 0xf2, 0x1a,
	0x19, 0x41, 0x4e, 0x9c, 0x60, 0x1e, 0x40, 0x9b, 0x75, 0xbb, 0x7d, 0x4d, 0xbb, 0x99, 0x8d, 0x0a,
	0x29, 0x2c, 0x43, 0xf1, 0x6d, 0x47, 0xd3, 0x7e, 0x98, 0xa8, 0x3d, 0xfd, 0xcd, 0x50, 0x7b, 0xd3,
	0x99, 0x76, 0x5f, 0x15, 0x14, 0xbc, 0x86, 0x87, 0xe3, 0x89, 0xce, 0xa5, 0xe1, 0x78, 0xa0, 0xab,
	0x7d, 0xad, 0x3f, 0xd5, 0xa7, 0x93, 0xd7, 0xfd, 0x71, 0x21, 0x4d, 0xa6, 0x50, 0xdb, 0x2b, 0x9a,
	0x8f, 0xd6, 0x7b, 0x7a, 0x72, 0x7c, 0x0a, 0x0e, 0x82, 0xf1, 0xc9, 0xc5, 0x97, 0xf7, 0x20, 0xe7,
	0xf0, 0xeb, 0xe4, 0x0f, 0x05, 0xae, 0x63, 0xdd, 0x4a, 0x12, 0x3a, 0x7b, 0x24, 0x3c, 0x91, 0x24,
	0x1c, 0xb9, 0xb3, 0x4f, 0x43, 0x37, 0xa0, 0xa1, 0x00, 0x0f, 0xd4, 0xfe, 0xf7, 0x93, 0xd7, 0xfd,
	0x9e, 0x3e, 0x9b, 0x0d, 0x7b, 0x85, 0x14, 0x16, 0xe1, 0xd2, 0x3f, 0x11, 0x79, 0x2a, 0x58, 0x82,
	0xc2, 0x78, 0xa2, 0x6b, 0x7d, 0x4d, 0x1b, 0x4e, 0xc6, 0xfa, 0xcd, 0x64, 0x36, 0xee, 0x15, 0x32,
	0xe4, 0x09, 0x14, 0x07, 0xd4, 0x3d, 0x6c, 0xdc, 0x70, 0x61, 0x0a, 0x81, 0x7c, 0x0b, 0x18, 0x36,
	0xbd, 0x73, 0x6b, 0x3d, 0x83, 0xac, 0xf7, 0xba, 0x88, 0x61, 0x4a, 0x25, 0xa1, 0xa5, 0xc8, 0x3e,
	0xf2, 0x7b, 0x6a, 0x01, 0x97, 0x91, 0x86, 0xc7, 0x0a, 0xe4, 0x78, 0xcb, 0x7b, 0xac, 0x65, 0x9a,
	0xf7, 0x55, 0x29, 0xe1, 0x0b, 0x00, 0xfa, 0x9b, 0x6d, 0x38, 0xa2, 0x98, 0xc5, 0xbc, 0xaa, 0xb5,
	0xc4, 0xb2, 0x6c, 0xf9, 0xcb, 0xb2, 0x35, 0xf5, 0x97, 0xa5, 0x1a, 0xb2, 0x26, 0x03, 0x38, 0x97,
	0x50, 0x93, 0x90, 0x85, 0x9e, 0x5a, 0x72, 0xe1, 0x59, 0xfe, 0xcc, 0x82, 0xbe, 0xe1, 0xff, 0xed,
	0x3f, 0xcf, 0x00, 0x6f, 0x76, 0x9b, 0x5b, 0xa3, 0xce, 0x47, 0x63, 0x41, 0xf1, 0x05, 0x9c, 0xcb,
	0x25, 0x8a, 0x65, 0x49, 0x4d, 0x74, 0x45, 0xd7, 0x2a, 0xfb, 0xc7, 0x82, 0x5a, 0x92, 0xc2, 0x2e,
	0xc0, 0x6e, 0x21, 0x61, 0x35, 0x52, 0x23, 0x61, 0x0f, 0x8f, 0x62, 0x34, 0x81, 0x13, 0x15, 0xae,
	0xf6, 0xb6, 0x00, 0x7e, 0x11, 0xb1, 0xdf, 0x5f, 0x46, 0xb5, 0x2f, 0x93, 0xd4, 0x81, 0x4f, 0x13,
	0xaa, 0x49, 0xd3, 0x0e, 0x1f, 0x47, 0x6e, 0x27, 0x8f, 0xc3, 0xda, 0x6d, 0x0d, 0x49, 0x0a, 0x7f,
	0x04, 0x9c, 0xd9, 0x4b, 0x99, 0x9b, 0x6f, 0x89, 0xf5, 0xe4, 0xc9, 0x21, 0x12, 0x69, 0x9c, 0x1a,
	0x2d, 0x24, 0x85, 0x23, 0xb8, 0x8c, 0x34, 0x1d, 0x5e, 0xc7, 0xb7, 0xa2, 0xf0, 0xf8, 0x79, 0xbc,
	0x32, 0xf0, 0xf6, 0x13, 0x7c, 0x16, 0xd3, 0xc2, 0xf8, 0xd5, 0xb1, 0xf6, 0x16, 0x9e, 0xc9, 0xe9,
	0x09, 0x20, 0x2a, 0x62, 0xd7, 0x84, 0x41, 0x45, 0x1c, 0xb4, 0x70, 0x50, 0x11, 0x87, 0x1d, 0x4b,
	0x52, 0xef, 0x72, 0x5c, 0xf7, 0xfc, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x76, 0x61, 0x77,
	0x69, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FingerprintServiceClient is the client API for FingerprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FingerprintServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	CreateGuestUser(ctx context.Context, in *CreateGuestUserRequest, opts ...grpc.CallOption) (*CreateGuestUserResponse, error)
	CreatePasswordResetToken(ctx context.Context, in *CreatePasswordResetTokenResponse, opts ...grpc.CallOption) (*CreatePasswordResetTokenResponse, error)
	UpdateUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*ResetUserPasswordResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	CreateSessionRevoke(ctx context.Context, in *CreateSessionRevokeRequest, opts ...grpc.CallOption) (*CreateSessionRevokeResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
}

type fingerprintServiceClient struct {
	cc *grpc.ClientConn
}

func NewFingerprintServiceClient(cc *grpc.ClientConn) FingerprintServiceClient {
	return &fingerprintServiceClient{cc}
}

func (c *fingerprintServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreateGuestUser(ctx context.Context, in *CreateGuestUserRequest, opts ...grpc.CallOption) (*CreateGuestUserResponse, error) {
	out := new(CreateGuestUserResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreateGuestUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreatePasswordResetToken(ctx context.Context, in *CreatePasswordResetTokenResponse, opts ...grpc.CallOption) (*CreatePasswordResetTokenResponse, error) {
	out := new(CreatePasswordResetTokenResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreatePasswordResetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) UpdateUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*ResetUserPasswordResponse, error) {
	out := new(ResetUserPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/UpdateUserPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) CreateSessionRevoke(ctx context.Context, in *CreateSessionRevokeRequest, opts ...grpc.CallOption) (*CreateSessionRevokeResponse, error) {
	out := new(CreateSessionRevokeResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/CreateSessionRevoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.FingerprintService/GetSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FingerprintServiceServer is the server API for FingerprintService service.
type FingerprintServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	CreateGuestUser(context.Context, *CreateGuestUserRequest) (*CreateGuestUserResponse, error)
	CreatePasswordResetToken(context.Context, *CreatePasswordResetTokenResponse) (*CreatePasswordResetTokenResponse, error)
	UpdateUserPassword(context.Context, *ResetUserPasswordRequest) (*ResetUserPasswordResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	CreateSessionRevoke(context.Context, *CreateSessionRevokeRequest) (*CreateSessionRevokeResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
}

func RegisterFingerprintServiceServer(s *grpc.Server, srv FingerprintServiceServer) {
	s.RegisterService(&_FingerprintService_serviceDesc, srv)
}

func _FingerprintService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreateGuestUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuestUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreateGuestUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreateGuestUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreateGuestUser(ctx, req.(*CreateGuestUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreatePasswordResetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePasswordResetTokenResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreatePasswordResetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreatePasswordResetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreatePasswordResetToken(ctx, req.(*CreatePasswordResetTokenResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/UpdateUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).UpdateUserPassword(ctx, req.(*ResetUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_CreateSessionRevoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).CreateSessionRevoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/CreateSessionRevoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).CreateSessionRevoke(ctx, req.(*CreateSessionRevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FingerprintService/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FingerprintService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FingerprintService",
	HandlerType: (*FingerprintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _FingerprintService_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _FingerprintService_CreateUser_Handler,
		},
		{
			MethodName: "CreateGuestUser",
			Handler:    _FingerprintService_CreateGuestUser_Handler,
		},
		{
			MethodName: "CreatePasswordResetToken",
			Handler:    _FingerprintService_CreatePasswordResetToken_Handler,
		},
		{
			MethodName: "UpdateUserPassword",
			Handler:    _FingerprintService_UpdateUserPassword_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _FingerprintService_CreateSession_Handler,
		},
		{
			MethodName: "CreateSessionRevoke",
			Handler:    _FingerprintService_CreateSessionRevoke_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _FingerprintService_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fingerprint.proto",
}
